.TH wut 7
.SH NAME
wut \- a cheatsheet organizer
.SH SYNOPSIS
.B wut
[\fI OPTIONS \fR]
[\fI SUBJECT \fR]
.SH DESCRIPTION
.B wut
(or "wot utility tool", wot being the abbreviation of "wut organized topic")
is a simple cheatsheet organizer. Notes are stored inside \fI~/.wut\fR and
can easily be pushed to a git repository, \fBwut\fR will create the commits for you.
If neither \fIOPTIONS\fR nor \fISUBJECT\fR has been given, \fBwut\fR will show
a tree of available sheets, subjects and notes. If a \fISUBJECT\fR is given without
\fIOPTIONS\fR, \fBwut\fR will show the contents of all notes within that subject. If
an argument - which is not a subject - is given without options, \fBwut\fR will
search all notes for the given term.
\fBwut\fR will load its configuration from \fI/etc/wut.conf\fR.
.SH OPTIONS
.TP
.BR \-i ", " \-\-init
Initialize workspace. This will create a folder - located in your home folder -
in which all the sheets, history and git data will be stored. If \fBgit\fR is
installed, a repository will be initialized within the folder.
.TP
.BR \-l ", " \-\-list
List notes.
.TP
.BR \-a ", " \-\-add\fR\ [\fIsheet\fR]\ [\fIsubject\fR]\ [\fInote\fR]
Add a new note. If either \fIsheet\fR, \fIsubject\fR or \fInote\fR is not
passed as an argument, wut will ask for them. Previous values for these
parameters will be used as default.
.TP
.BR \-e ", " \-\-edit\fR\ [\fIsheet\fR]\ [\fIsubject\fR]\ [\fInote\fR]
Edit an existing note. If either \fIsheet\fR, \fIsubject\fR or \fInote\fR is not
passed as an argument, wut will ask for them. Previous values for these
parameters will be used as default.
.TP
.BR \-d ", " \-\-delete\ \fIsheet\fR\ [\fIsubject\fR\ [\fInote\fR]]
Delete a sheet, subject or note.
.TP
.BR \-g ", " \-\-git\ \fIgit-command-args\fR
If the sheet store is a git repository, execute a git command specified by
git-command-args.
.TP
.BR \-h ", " \-\-help ", " \-\-wut
Show the program help.
.TP
.BR \-v ", " \-\-version
Show version information.
.SH AUTHOR
.B wut
was written by Joris Hartog.
.SH "SEE ALSO"
.BR git (1)
